steps:
- id: 'print'
  name: 'ubuntu'
  entrypoint: 'bash'  
  args: 
  - '-c'
  - | 
      echo "******************"
      echo "$BRANCH_NAME"
      echo "******************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'init']

- id: 'tf plan'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'plan' ]
  
- id: 'tf apply'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'plan' ]
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "******************"
      echo "SKIP APPLY $BRANCH_NAME"
      echo "******************"
