steps:
- id: 'tf validate'
  name: 'ubuntu'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
     echo "====================================" 
     echo "Installing environment $BRANCH_NAME"
     echo "====================================" 

- id: 'tf init'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'init']

- id: 'tf apply'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'apply', '-auto-approve']
