steps:
- id: 'logging'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "******************"
      echo "$BRANCH_NAME"
      echo "******************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'init']

- id: 'tf plan'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'plan' ]
  
- id: 'tf apply'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  entrypoint: 'ash'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "prod" ] ; then
        terraform apply -auto-approve
      else
        echo "********************************** SKIPPING APPLYING **********************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "***************************************************************************************"
      fi
