steps:
- id: 'logging'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "******************"
      echo "$BRANCH_NAME"
      echo "******************"

- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "prod" ] ; then
        cd environments/$BRANCH_NAME
        terraform init
      else
        cd environments/master && terraform init
        cd ../prod && terraform init
      fi 

- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "prod" ] ; then
        cd environments/$BRANCH_NAME
        terraform plan
      else
        cd environments/master && terraform plan
        cd ../prod && terraform plan
      fi  
  
- id: 'tf apply'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "prod" ] ; then
        terraform apply -auto-approve
      else
        echo "********************************** SKIPPING APPLYING **********************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "***************************************************************************************"
      fi
