steps:
- id: 'print'
  name: 'ubuntu'
  entrypoint: 'bash'  
  args: 
  - '-c'
  - | 
      echo "******************"
      echo "$BRANCH_NAME"
      echo "******************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'init']

# - id: 'tf plan'
#   name: 'hashicorp/terraform'
#   dir: environments/$BRANCH_NAME
#   args: [ 'plan' ]
  
- id: 'tf apply'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [[ " master prod " =~ .*\ $BRANCH_NAME\ .* ]]; then
        echo "******************"
        echo "APPLY $BRANCH_NAME"
        echo "******************"
      else
        echo "******************"
        echo "SKIP $BRANCH_NAME"
        echo "******************"
      fi
