steps:
- id: 'print'
  name: 'ubuntu'
  args: 
  - '-c'
  - | 
      echo "******************"
      echo "$BRANCH_NAME"
      echo "******************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'init']

- id: 'tf plan'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'plan' ]
