steps:
- id: 'env'
  name: 'alphine'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
     echo "Installing environment $BRANCH_NAME"

- id: 'tf init'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'init']

- id: 'tf apply'
  name: 'hashicorp/terraform'
  dir: environments/$BRANCH_NAME
  args: [ 'apply', '-auto-approve']
